# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Statemate < Formula
  desc "Declarative system configuration management"
  homepage "https://github.com/subbeh/statemate"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/subbeh/statemate/releases/download/v0.2.0/statemate_0.2.0_darwin_amd64.tar.gz"
      sha256 "86326d361a402141e60fc4933a1da7952f8d8f285f38dbc6c5af8e4c20b23f3d"

      define_method(:install) do
        bin.install "mate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/subbeh/statemate/releases/download/v0.2.0/statemate_0.2.0_darwin_arm64.tar.gz"
      sha256 "057a404b664acc7f44e234fb843e61f290a2f1c1139429a3a229e14fbb8d8988"

      define_method(:install) do
        bin.install "mate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/subbeh/statemate/releases/download/v0.2.0/statemate_0.2.0_linux_amd64.tar.gz"
      sha256 "a80f282acf4f105b27a278890be83a00134acb8d93a08995207882b3f764ca81"
      define_method(:install) do
        bin.install "mate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/subbeh/statemate/releases/download/v0.2.0/statemate_0.2.0_linux_arm64.tar.gz"
      sha256 "876d8954a592d8c0743cfdcea85e9bc12621e43ed41e2e97d897b73233ac8858"
      define_method(:install) do
        bin.install "mate"
      end
    end
  end

  test do
    system "#{bin}/mate", "--version"
  end
end
