# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Statemate < Formula
  desc "Declarative system configuration management"
  homepage "https://github.com/subbeh/statemate"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/subbeh/statemate/releases/download/v0.5.0/statemate_0.5.0_darwin_amd64.tar.gz"
      sha256 "116bc626fad27d39a72b78751b93cd6025bd983740fcd71f93646cf41e884157"

      define_method(:install) do
        bin.install "mate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/subbeh/statemate/releases/download/v0.5.0/statemate_0.5.0_darwin_arm64.tar.gz"
      sha256 "599c882a28307d6a441cd97b231cc4d3b55e68af80bcb2eb41a7edb26f9dde05"

      define_method(:install) do
        bin.install "mate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/subbeh/statemate/releases/download/v0.5.0/statemate_0.5.0_linux_amd64.tar.gz"
      sha256 "e278517475060fedea36917f24a0541a0ec055d233bf12f6668f69d786cdcd57"
      define_method(:install) do
        bin.install "mate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/subbeh/statemate/releases/download/v0.5.0/statemate_0.5.0_linux_arm64.tar.gz"
      sha256 "5bfcd090daef3309b2eff5e9149ae42808c1d584876a739ccad23532d49d8e64"
      define_method(:install) do
        bin.install "mate"
      end
    end
  end

  test do
    system "#{bin}/mate", "--version"
  end
end
